server:
  address:     ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

logger:
  level : "all"
  stdout: true

database:
  default:
    - link: "mysql:root:gyc1993@tcp(114.115.135.233:3306)/sviwo" #数据库url配置
      role: "master"

redis:
  default:
    address: 127.0.0.1:7001 #redis地址
    db:      1 #db
    pass: #密码
  cache:
    address: 127.0.0.1:7001  #地址
    db: 1   #db
    pass:  #密码



