// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "sviwo/internal/logic/admin"
	_ "sviwo/internal/logic/bizctx"
	_ "sviwo/internal/logic/login"
	_ "sviwo/internal/logic/middleware"
	_ "sviwo/internal/logic/permission"
	_ "sviwo/internal/logic/role"
	_ "sviwo/internal/logic/session"
	_ "sviwo/internal/logic/user"
)
